### ISSUE TITLE
Search doesn't work anymore on https://docs.humhub.org/

### ISSUE THREAD

**Issue by marc-farre** [humhub/documentation#101]
E.g, https://docs.humhub.org/search?q=group

![image](https://github.com/humhub/documentation/assets/23310825/8a6f73de-e4e2-4f87-9cd0-d5355612b310)

**Comment by luke-** [comment]
Can you please take a look here? As before the Docusaurus update, we replace the AppKey during deployment. Have there been any changes here?

```    
{
      apiKey: 'xxx',
      appId: 'humhub',
      indexName: 'humhub',
    },
```

**Comment by serh-mosk** [comment]
@luke- According to the error log: 'Unreachable hosts - your application id may be incorrect. If the error persists, contact support@algolia.com.' - incorrect application id. I think you need to specify your current Algolia appID and appKey in the docusaurus config. To see your appId, you need to log in to your Algolia account. You can find them here - https://dashboard.algolia.com/account/api-keys/all?applicationId=<appId>

**Comment by marc-farre** [comment]
Any news about this issue? Thanks!

**Comment by luke-** [comment]
@serh-mosk Can you check here whether we could somehow use a integrated Docusaurus Search? I don't really want to integrate a third-party service here unless absolutely necessary.

**Comment by marc-farre** [comment]
Still not working. It's quite difficult to find relevant information in a documentation without a search engine... Thanks!

**Comment by luke-** [comment]
@gevorgmansuryan Can you please take a look at this?

I would prefer if we could use the internal search of Docusaurus or something of our own (not cloud based/cost free).

**Comment by luke-** [comment]
@gevorgmansuryan Thanks, works fine!

**Comment by marc-farre** [comment]
@gevorgmansuryan thanks!
