### ISSUE TITLE
Add recommended cron jobs to the doc

### ISSUE THREAD

**Issue by marc-farre** [humhub/documentation#107]
The idea: in https://docs.humhub.org/docs/admin/cron-jobs#cronjob-configuration, recommend adding 2 daily cron jobs (optional of course):

```sh
0 2 * * * /usr/bin/php /path/to/humhub/protected/yii integrity/run --interactive=0 >/dev/null 2>&1
0 3 * * * /usr/bin/php /path/to/humhub/protected/yii module/update-all >/dev/null 2>&1
```

@luke- do you think it's a good idea?
If yes, I can send a PR.

**Comment by luke-** [comment]
Hmm, not sure...  But maybe we could add this to the Community Wiki as a tip & trick.

If we implement an Auto Update or Auto IntegrityCheck in the core at some point, it should be possible without a separate CronJob.

**Comment by marc-farre** [comment]
Done here: https://community.humhub.com/content/perma?id=276298
