### ISSUE TITLE
The language code list is not updated

### ISSUE THREAD

**Issue by marc-farre** [humhub/documentation#140]
URL: https://docs.humhub.org/docs/admin/translations/#overwrite-translation-messages

E.g.: `en-UK` should be `en-GB` (see https://community.humhub.com/comment/perma?id=49959)

Should we fix this list, or should we remove it and give the URL of it?
https://github.com/humhub/humhub/blob/master/protected/humhub/config/common.php -> `availableLanguages`

I would opt for the 2nd option, because we might forget to maintain this list updated, mainly when adding new languages.

**Comment by luke-** [comment]
@marc-farre Yes, your second idea is better. Would you like to remove it and insert a link?
