### ISSUE TITLE
Translations for password rules don't work as described

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/documentation#52]
In the page Security ([https://github.com/humhub/documentation/blob/master/docs/admin/security.md](https://github.com/humhub/documentation/blob/master/docs/admin/security.md)) it is described how to set your own password rules and for translations it says:

> To localize error message you have to define a new message file with the following path pattern:
> `protected/humhub/messages/<language>/custom.php`

 This didn't work for me. Now I added my translation to `/protected/config/messages/<language>/UserModule.custom.php` and this works.
 Maybe you can check that and change it in the documentation.

Q | A
-- | --
HumHub version | 1.9.1
PHP version |  8.0.10
Operating system |  Ubuntu 20.04 with Plesk Obsidian v18.0.3

**Comment by luke-** [comment]
Thanks, looks really like a bug in the docs. Your path seems to tbe correct.

**Comment by yurabakhtin** [comment]
@luke- I also detected if works with path `protected/humhub/modules/user/messages/<language>/custom.php`, so I added this too - https://github.com/humhub/documentation/commit/7b59307a0f5bc52190e00659cda748e1c8f03185.

**Comment by luke-** [comment]
@yurabakhtin Thanks, since `protected/humhub/*` will be overwritten during updates, we should not recommend this. `protected/config` is the preferred way.

**Comment by yurabakhtin** [comment]
@luke- Ok, then I removed that in commit https://github.com/humhub/documentation/commit/488e5f16635a7a29355bd77c5921edcec8db9546.

**Comment by luke-** [comment]
Thanks!
