### ISSUE TITLE
"Modules & Marketplace" page outdated

### ISSUE THREAD

**Issue by marc-farre** [humhub/documentation#79]
On https://docs.humhub.org/docs/admin/modules#purchased-modules we have:

> Purchased modules can be activated via the Administration -> Modules -> Purchase page.
> They are then available for installation in the Browse Online tab.

This should be updated, but:
- It's complicated to explain with the new method
- perhaps we should wait for the new module manager to come

**Comment by marc-farre** [comment]
@Semir1212 @luke- what do you think about this PR?
https://github.com/humhub/documentation/pull/111

**Comment by Semir1212** [comment]
@marc-farre Thank you, @mbumpalumpa will look into it and also provide some screenshots to make it easier for the users.

**Comment by Semir1212** [comment]
What do you think about the new PR @marc-farre? 

#114

**Comment by marc-farre** [comment]
@mbumpalumpa thanks, it's awesome!

I've added a commit: https://github.com/humhub/documentation/pull/114/commits/9502d7a38048ee91e170740c7d0d6609736a04ef

Because, when you install a new custom module by manually unzipping it, you don't need to perform database migrations (it's done when the module is enabled).
But DB migrations can be required after updating the module.

So if you agree with my commit, maybe we could remove the screenshot related to DB migrations, or if not, we should add one for flushing cache. But both procedures might change in a future HumHub versions as the Information page might be reworked.

**Comment by Semir1212** [comment]
Both approaches would be fine for me @marc-farre 

Just pick the one you prefer and adapt the screenshots @mbumpalumpa

**Comment by marc-farre** [comment]
@mbumpalumpa Thanks, it's perfect!
